language: python

python:
    - "2.7"
    - "3.4"

before_install:
    - sudo apt-get install python3-pip
    
install:
  - sudo python3 -m pip install mypy
  - sudo pip install -r requirements.txt
  
script:
    - python main.py test
    - python main.py mypy
